# ci/tasks/zap-af.yml
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((repo_name)) # built FROM ${base_image}
    tag: ((runner_tag))

inputs:
  - name: zap-runner
  - name: auth

outputs:
  - name: zap-reports

params:
  SCAN_CONTEXT:
  AUTH_TOKEN_FILE:

run:
  path: bash
  args:
    - -euo
    - pipefail
    - zap-runner/ci/tools/run-zap-af.sh
