# Unauthenticated public scanning
AUTH_TYPE: none
SCAN_TYPE: baseline
SPIDER_MAX_DEPTH: 5
MAX_SCAN_DURATION: 45
ALERT_THRESHOLD: LOW
# Note: User-Agent is centrally managed (ci/common/user-agent.txt or pipeline var).
# Global exclusions are centrally managed (ci/common/global-exclusions.txt).
