name: "OWASP ZAP Full DAST"
description: "Traditional & AJAX Spider, Passive & Active scanning with multi-format reports"

progressToStdout: true # Stream progress to console

name: "OWASP ZAP Context-Aware DAST"
description: "Spider + Active/Passive scan per URL with multi-format reports"
progressToStdout: true

jobs:
  - type: spider
    parameters:
      maxDepth: 5
      threadCount: 2

  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
      scanOnlyInScope: true

  - type: passiveScan-wait
    parameters:
      maxDuration: 60

  - type: activeScan
    parameters:
      policy: "Default Policy"
      maxScanDurationInMins: 0

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk"
      reportFile: "{{yyyy-MM-dd}}-[[site]]-html.html"
      displayReport: false
    risks:
      - high
      - medium
      - low
  #      - info
    confidences:
      - high
      - medium
#      - low
#      - falsepositive

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk"
      reportFile: "{{yyyy-MM-dd}}-[[site]]-json.json"
      displayReport: false
      risks:
        - high
        - medium
        - low
  #     - info
      confidences:
        - high
        - medium
    #   - low
    #   - falsepositive

  - type: report
    parameters:
      template: "traditional-xml"
      reportDir: "/zap/wrk"
      reportFile: "{{yyyy-MM-dd}}-[[site]]-xml.xml"
      displayReport: false
      risks:
        - high
        - medium
        - low
    #      - info
      confidences:
        - high
        - medium
  #      - low
  #      - falsepositive

  - type: report
    parameters:
      template: "sarif-json"
      reportDir: "/zap/wrk"
      reportFile: "{{yyyy-MM-dd}}-[[site]]-sarif.sarif.json"
      displayReport: false
      risks:
        - high
        - medium
        - low
    #      - info
      confidences:
        - high
        - medium
  #      - low
  #      - falsepositive

  - type: exitStatus
    parameters:
      warnLevel: MEDIUM
      errorLevel: HIGH
