# ci/pipeline.yml
---
jobs:
  - name: set-self
    plan:
      - get: ((repo_name))
        trigger: true

      - set_pipeline: zap-scanner
        file: ((repo_name))/ci/pipeline.yml
        var_files:
          - ((repo_name))/ci/config.yml

  - name: scan-all-contexts
    plan:
      - get: zap-config
        trigger: true

      - get: zap-runner
        trigger: true
        passed: [set-self]

      - across:
          - var: mode
            # will loop 4 contexts, but scan only those URLs present
            values: ["internal", "external", "pages", "unauthenticated"]
        max_in_flight: all
        fail_fast: false
        do:
          - task: zap-scan
            file: zap-runner/ci/tasks/zap-scan.yml
            vars:
              repo_name: ((repo_name))
              runner_tag: ((runner_tag))
            params:
              SCAN_MODE: ((.:mode))
              CREDHB_CRED: ((credentials.$SCAN_MODE))

groups:
  - name: default
    jobs:
      - set-self
      - scan-all-contexts

resources:
  - name: zap-runner
    type: git
    source:
      uri: https://github.com/cloud-gov/((repo_name))
      branch: main
      commit_verification_keys: ((cloud-gov-pgp-keys))
      ignore_paths: ["Dockerfile"]

  - name: zap-config
    type: git
    source:
      uri: https://github.com/cloud-gov/zap-runner
      branch: main
      paths:
        - ci/zap-config/**

#  - name: daily
#    type: time
#    source:
#      interval: 12h

resource_types:
  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: git
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: git-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: time
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: time-resource
      aws_region: us-gov-west-1
      tag: latest
