---
jobs:
  - name: set-self
    plan:
      - get: zap-runner
        trigger: true

      - set_pipeline: zap-scanner
        file: zap-runner/ci/pipeline.yml
        var_files:
          - zap-runner/ci/config.yml

  - name: scan-all-contexts
    plan:
      - get: zap-config
        trigger: true

      - get: zap-runner
        trigger: true
        passed: [set-self]

      - across:
          - var: context
            values: ["internal", "external", "pages", "unauthenticated"]
        limit: all
        fail_fast: false
        do:
          - task: zap-scan
            file: zap-runner/ci/tasks/zap-scan.yml
            vars:
              repo_name: ((repo_name))
              runner_tag: ((runner_tag))
            params:
              TARGET_CONTEXT: ((.:context))
              CREDHB_CRED: ((credentials))

groups:
  - name: default
    jobs:
      - set-self
      - scan-all-contexts

resources:
  - name: zap-config
    type: git
    source:
      uri: https://github.com/cloud-gov/zap-runner.git
      branch: main
      paths:
        - ci/zap-config/**

  - name: zap-runner
    type: git
    source:
      uri: https://github.com/cloud-gov/((repo_name))
      branch: main
      commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: git
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: git-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: time
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: time-resource
      aws_region: us-gov-west-1
      tag: latest
